version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_HOST: 'db'
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: app_name_test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Wait for DB
          # circleci/* の Docker イメージにプリインストール
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: MySQL version
          command: bundle exec rails db:schema:load --trace
      - run: 
          name: rspec test
          command: bundle exec rspec
      - run: 
          name: rubocop test
          command: rubocop

workflows:
  version: 2
  workflows:
    jobs:
      - test